### ISSUE TITLE
Error trigged  in developer tools for  fuzzy definitions plugin(F12) loaded with new updates.

### ISSUE THREAD

**Issue by vinod-a-ext** [jrieken/fuzzy-definitions#1]
![image](https://cloud.githubusercontent.com/assets/12810078/15285510/20f133ce-1b75-11e6-87f1-91c025837148.png)

**Comment by jrieken** [comment]
@vinod-a-ext any chance you can share that workspace with me?

**Comment by vinod-a-ext** [comment]
Sorry buddy ..private repository

**Comment by jrieken** [comment]
this should now work given you have a recent version of nodejs on your path. please give it another try

**Comment by jrieken** [comment]
was closed with https://github.com/jrieken/fuzzy-definitions/commit/686a160734455f9ec8e337f425f064f5a292659a
